feat: Add core models shared between shipping and carrier-gateway
ShipitSmarter/ShipitSmarter.Core pull request #31
Opened 2024-01-22 16:49 UTC by LennartKoot

2024-01-24 08:19 UTC, Droxx commented
I've found some items that should be included in core. I will update this comment with them as i find them. (and strike them through once added)

* DocumentType

2024-01-24 08:25 UTC, Droxx commented
Also @LennartKoot are we going to keep a constructor in the Address model? should this not be removed as it interferes with YamlDotNet?

2024-01-25 13:45 UTC, ThumNet requested changes

2024-01-25 13:45 UTC, ThumNet commented on src/ShipitSmarter.Core/Models/v1/Incoterms.cs
> +    [Required]
Should we use RequiredNotDefault here?

2024-01-25 13:48 UTC, ThumNet approved these changes

2024-01-25 13:50 UTC, merged